# Name of our action
name: 'Chromatic'
on: 
  push:
    branches:
      - master
    paths: 
    - 'packages/**'
    - '!packages/docs'

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn

      - name: Build packages
        run: yarn build

      - name: Run tests
        run: yarn test:ci

      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          workingDir: packages/docs
          exitZeroOnChanges: true
