name: Issue workflow

on:
  issues:
    types: [opened, assigned, closed]

jobs:
  issue_opened:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        if: github.event.action == 'opened'
        with:
          project: pepe-ui
          column: To do 
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  issue_assigned:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        if: github.event.action == 'assigned'
        with:
          project: pepe-ui
          column: In progress
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  issue_closed:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: pepe-ui
          column: Done
          repo-token: ${{ secrets.GITHUB_TOKEN }}